schoolapp/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.home,name='home'),
    path('login',views.login,name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('details', views.details, name='details'),
    path('get-courses/', views.get_courses, name='get_courses'),
    path('success/', views.success, name='success'),

]

schoolproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schoolapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

schoolapp/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Course(models.Model):
    department = models.ForeignKey(Department,on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name



class Details(models.Model):
    name = models.CharField(max_length=20)
    date_of_brith = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    phone = models.IntegerField
    email = models.EmailField()
    address = models.CharField(max_length=300)
    department = models.ForeignKey(Department,on_delete=models.SET_NULL,null=True)
    course = models.ForeignKey(Course,on_delete=models.SET_NULL,null=True)
    purpose = models.CharField(max_length=20)
    materials_provide = models.CharField(max_length=300)

    def __str__(self):
        return self.name

schoolapp/forms.py
from django import forms

from .models import Details

select_gender = (
    ("male", "Male"),
    ("female", "Female"),
    ("other", "Other"),
)

select_purpose = (
    ("Order", "order"),
    ("Return ", "return ")
)

select_materials_provide = (
    ("Note Book", "note book"),
    ("Pen", "pen"),
    ("Exam Peppers", "exam peppers")
)


class DateInput(forms.DateInput):
    input_type = 'date'


class DetailsForms(forms.ModelForm):
    class Meta:
        model = Details
        fields = '__all__'
        widgets = {
            "gender": forms.RadioSelect(choices=select_gender),
            "date_of_brith": DateInput,
            "materials_provide": forms.CheckboxSelectMultiple(choices=select_materials_provide),
            "purpose": forms.Select(choices=select_purpose),
            "department": forms.Select(),
            "course": forms.Select(),
        }

schoolapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import DetailsForms
from django.http import JsonResponse
from .models import Course

# Create your views here.
def home(request):
    return render(request,'index.html')

def login(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid credentials')
            return redirect('login')

    return render(request,'login.html')

def register(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username taken")
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save();
                print('user created')
                return redirect('login')
        else:
            messages.info(request,"password not matched")
            return redirect('register')

    return render(request,'register.html')


def logout(request):
    auth.logout(request)
    return redirect('/')


def details(request):
    if request.method == 'POST':
        form = DetailsForms(request.POST)
        if form.is_valid():
            form.save()
            confirmation_message = "Order Confirmed"
            return render(request, 'details.html', {'confirmation_message': confirmation_message})
    else:
        form = DetailsForms()
    return render(request,'details.html',{'form':form})




def get_courses(request):
    department_id = request.GET.get('department_id')
    courses = Course.objects.filter(department_id=department_id)
    course_list = [{'id': course.id, 'name': course.name} for course in courses]
    return JsonResponse(course_list, safe=False)

def success(request):
    return render(request, 'success.html')

templates/content.html
{% extends 'index.html' %}
{% load static %}
{% block content1 %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

.input-container {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  width: 100%;
  margin-bottom: 15px;
}

.icon {
  padding: 10px;
  background: #17a2b8;
  color: white;
  min-width: 50px;
  text-align: center;
}

.input-field {
  width: 100%;
  padding: 10px;
  outline: none;
}

.input-field:focus {
  border: 2px solid #17a2b8;
}

/* Set a style for the submit button */
.btn1 {
  background-color: #17a2b8;
  color: white;
  padding: 15px 20px;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.btn:hover {
  opacity: 1;
}
</style>
{% endblock content1 %}
{% block content %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<a href="{% url 'home' %}">Return to Home Page</a>


{% endblock %}

templates/details.html
{% extends 'index.html' %}
{% load static %}
{% block content1 %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

.input-container {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  width: 100%;
  margin-bottom: 15px;
}

.icon {
  padding: 10px;
  background: #17a2b8;
  color: white;
  min-width: 50px;
  text-align: center;
}

.input-field {
  width: 100%;
  padding: 10px;
  outline: none;
}

.input-field:focus {
  border: 2px solid #17a2b8;
}

/* Set a style for the submit button */
.btn1 {
  background-color: #17a2b8;
  color: white;
  padding: 15px 20px;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.btn:hover {
  opacity: 1;
}
</style>
{% endblock content1 %}
{% block content %}
<div class="container-fluid pt-5">
{% if confirmation_message %}
    <p>{{ confirmation_message }}</p>
    <a href="{% url 'home' %}">Return to Home Page</a>
{% else %}
<form style="max-width:500px;margin:auto" method="post" enctype="multipart/form-data">
  {% csrf_token %}
    <table>
        {{form.as_table}}
        {{form.errors}}
    </table>



  <button type="submit" class="btn1">register </button>
</form>
{% endif %}

</div>
<script>
        $(document).ready(function() {
            $('#id_department').change(function() {
                var departmentId = $(this).val();
                $.ajax({
                    url: '/get-courses/',
                    data: {
                        'department_id': departmentId
                    },
                    dataType: 'json',
                    success: function(data) {
                        var courseSelect = $('#id_course');
                        courseSelect.empty();
                        courseSelect.append('<option value="">Select Course</option>');
                        $.each(data, function(index, value) {
                            courseSelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                        });
                    }
                });
            });
        });
</script>
{% endblock %}

templates/login.html
{% extends 'index.html' %}
{% load static %}
{% block content1 %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

.input-container {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  width: 100%;
  margin-bottom: 15px;
}

.icon {
  padding: 10px;
  background: #17a2b8;
  color: white;
  min-width: 50px;
  text-align: center;
}

.input-field {
  width: 100%;
  padding: 10px;
  outline: none;
}

.input-field:focus {
  border: 2px solid #17a2b8;
}

/* Set a style for the submit button */
.btn1 {
  background-color: #17a2b8;
  color: white;
  padding: 15px 20px;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.btn:hover {
  opacity: 1;
}
</style>
{% endblock content1 %}
{% block content %}
<div class="container-fluid pt-5">
<form action="login" style="max-width:500px;margin:auto" method="post">
  {% csrf_token %}
  <h2>please login</h2>
  <div class="input-container">
    <i class="fa fa-user icon"></i>
    <input class="input-field" type="text" placeholder="Username" name="username">
  </div>



  <div class="input-container">
    <i class="fa fa-key icon"></i>
    <input class="input-field" type="password" placeholder="Password" name="password">
  </div>


  <button type="submit" class="btn1">login</button>
</form>
<div class="container-fluid pt-5">
      <div class="container">
        <div class="text-center pb-2">
                   <a href="{% url 'register' %}" class="btn btn-primary px-4">register</a>

        </div>
      </div>
</div>
  {% for msg in messages %}
  {{msg}}
  {% endfor %}

</div>

{% endblock %}

templates/register.html
{% extends 'index.html' %}
{% load static %}
{% block content1 %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

.input-container {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  width: 100%;
  margin-bottom: 15px;
}

.icon {
  padding: 10px;
  background: #17a2b8;
  color: white;
  min-width: 50px;
  text-align: center;
}

.input-field {
  width: 100%;
  padding: 10px;
  outline: none;
}

.input-field:focus {
  border: 2px solid #17a2b8;
}

/* Set a style for the submit button */
.btn1 {
  background-color: #17a2b8;
  color: white;
  padding: 15px 20px;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.btn:hover {
  opacity: 1;
}
</style>
{% endblock content1 %}
{% block content %}
<div class="container-fluid pt-5">
<form action="register" style="max-width:500px;margin:auto" method="post">
  {% csrf_token %}
  <h2>please register</h2>
  <div class="input-container">
    <i class="fa fa-user icon"></i>
    <input class="input-field" type="text" placeholder="Username" name="username">
  </div>
    <div class="input-container">
    <i class="fa fa-key icon"></i>
    <input class="input-field" type="password" placeholder="Password" name="password">
  </div>


  <div class="input-container">
    <i class="fa fa-key icon"></i>
    <input class="input-field" type="password" placeholder="Confirm Password" name="cpassword">
  </div>


  <button type="submit" class="btn1">register </button>
</form>
{% for msg in messages %}
  {{msg}}
{% endfor %}

</div>

{% endblock %}

templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>gg</title>
</head>
<body>
hhggjh
</body>
</html>